#!/usr/bin/env bash
# Build natively for amd64 (here) and arm64 (on the arm builder), then push
# binaries, the systemd user unit and per-node configs to every host.
#   scripts/deploy-cluster.sh              build + push to all hosts
#   scripts/deploy-cluster.sh --no-build   push existing dist/ only
#   scripts/deploy-cluster.sh --restart    also restart the user service
# Never touches real data: trial layout only (scripts/cluster.env).
set -euo pipefail
cd "$(dirname "$0")/.."
source scripts/cluster.env

build=1 restart=0
for a in "$@"; do
  case "$a" in
    --no-build) build=0 ;;
    --restart) restart=1 ;;
    *) echo "unknown option $a" >&2; exit 2 ;;
  esac
done

if [ "$build" = 1 ]; then
  scripts/build.sh
  echo "== syncing source to $SPARKNEST_ARM_BUILDER"
  ssh "$SPARKNEST_ARM_BUILDER" "mkdir -p $SPARKNEST_ARM_BUILD_DIR"
  rsync -a --delete --exclude target --exclude dist --exclude .git --exclude web/node_modules \
    ./ "$SPARKNEST_ARM_BUILDER:$SPARKNEST_ARM_BUILD_DIR/"
  ssh "$SPARKNEST_ARM_BUILDER" "cd $SPARKNEST_ARM_BUILD_DIR && scripts/build.sh"
  mkdir -p dist/aarch64
  rsync -a "$SPARKNEST_ARM_BUILDER:$SPARKNEST_ARM_BUILD_DIR/dist/aarch64/" dist/aarch64/
fi

members=""
for h in "${SPARKNEST_HOSTS[@]}"; do
  IFS=: read -r name id ip _ <<<"$h"
  members+="  { id = $id, name = \"$name\", addr = \"$ip:$SPARKNEST_PORT\" },"$'\n'
done

secret_local="dist/cluster.secret.$SPARKNEST_CLUSTER"
[ -f "$secret_local" ] || { head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n' > "$secret_local"; chmod 600 "$secret_local"; }

for h in "${SPARKNEST_HOSTS[@]}"; do
  IFS=: read -r name id ip arch <<<"$h"
  echo "== $name ($arch)"
  cfg=$(mktemp)
  cat > "$cfg" <<CFG
# Generated by scripts/deploy-cluster.sh
[node]
id = $id
name = "$name"
state_dir = "$SPARKNEST_STATE_DIR"
mountpoint = "$SPARKNEST_MOUNT"
listen = "$ip:$SPARKNEST_PORT"
api_listen = "$ip:$SPARKNEST_API_PORT"

[cluster]
name = "$SPARKNEST_CLUSTER"
secret_file = "$SPARKNEST_STATE_DIR/cluster.secret"
members = [
$members]
CFG
  ssh "$name" "mkdir -p $SPARKNEST_BIN_DIR ~/.config/systemd/user && test -w $SPARKNEST_STATE_DIR" \
    || { echo "   $SPARKNEST_STATE_DIR missing or not writable on $name (see docs/ENVIRONMENT.md root checklist)"; rm -f "$cfg"; continue; }
  rsync -a "dist/$arch/" "$name:$SPARKNEST_BIN_DIR/"
  rsync -a "$cfg" "$name:$SPARKNEST_STATE_DIR/node.toml"
  rsync -a --chmod=F600 "$secret_local" "$name:$SPARKNEST_STATE_DIR/cluster.secret"
  sed -e "s#@BIN_DIR@#${SPARKNEST_BIN_DIR/#\~/%h}#g" -e "s#@STATE_DIR@#$SPARKNEST_STATE_DIR#g" -e "s#@MOUNT@#$SPARKNEST_MOUNT#g" \
    packaging/systemd/sparknestd.service | ssh "$name" "cat > ~/.config/systemd/user/sparknestd-$SPARKNEST_CLUSTER.service"
  ssh "$name" "systemctl --user daemon-reload"
  # Stage the system unit (passthrough needs CAP_SYS_ADMIN; see ENVIRONMENT.md).
  home=$(ssh "$name" 'echo $HOME')
  user=$(ssh "$name" 'id -un'); group=$(ssh "$name" 'id -gn')
  sed -e "s#@BIN_DIR@#${SPARKNEST_BIN_DIR/#\~/$home}#g" -e "s#@STATE_DIR@#$SPARKNEST_STATE_DIR#g" \
      -e "s#@MOUNT@#$SPARKNEST_MOUNT#g" -e "s#@USER@#$user#g" -e "s#@GROUP@#$group#g" \
    packaging/systemd/sparknestd@.service \
    | ssh "$name" "mkdir -p ~/.config/sparknest && cat > ~/.config/sparknest/sparknestd@$SPARKNEST_CLUSTER.service"
  if [ "$restart" = 1 ]; then
    ssh "$name" "systemctl --user restart sparknestd-$SPARKNEST_CLUSTER.service"
  fi
  rm -f "$cfg"
done
echo "deployed $SPARKNEST_CLUSTER cluster"
