#!/usr/bin/env bash
# Install sparknest with Homebrew on every host and configure the real
# cluster (not the trial). Nothing is published: the formula is rendered
# against a source tarball of the committed HEAD and installed from a local
# tap on each host.
#
#   scripts/install-cluster.sh package     tarball + formula in dist/local-brew/
#   scripts/install-cluster.sh install [HOST...]  brew-build it on every host
#                                          (or those), in parallel
#   scripts/install-cluster.sh configure   node.toml + secret in /srv/sparknest,
#                                          system unit staged in ~/.config/sparknest/
#   scripts/install-cluster.sh all         the three in order
#
# Then, once per host (root): install and enable the staged system unit, see
# the commands printed at the end. The first host is bootstrapped by hand
# (docs/INSTALL.md, "Start").
set -euo pipefail
cd "$(dirname "$0")/.."
source scripts/cluster.env # hosts and ids

CLUSTER=sparknest
STATE=/srv/sparknest
MOUNT=/mnt/sparknest
PORT=7400
API_PORT=7401
TAP=tj/sparknest-local
BREW=/home/linuxbrew/.linuxbrew/bin/brew
BIN=/home/linuxbrew/.linuxbrew/opt/sparknest/bin
DIST_REMOTE='$HOME/sparknest-dist'

version=$(sed -n 's/^version = "\(.*\)"$/\1/p' Cargo.toml | head -1)
name="sparknest-$version"
out=dist/local-brew

package() {
  [ -z "$(git status --porcelain)" ] || { echo "working tree is not clean; commit first" >&2; exit 1; }
  mkdir -p "$out"
  git archive --format=tar --prefix="$name/" HEAD | gzip -n > "$out/$name.tar.gz"
  local sha home
  sha=$(sha256sum "$out/$name.tar.gz" | cut -d' ' -f1)
  home=$(ssh "${SPARKNEST_HOSTS[0]%%:*}" 'echo $HOME')
  {
    echo "# Local build of sparknest $version ($(git rev-parse --short HEAD)); not published."
    sed -e '1,3d' \
        -e "s#@URL@#file://$home/sparknest-dist/$name.tar.gz#" \
        -e "s#@SHA256@#$sha#" \
        -e "s#^class Sparknest < Formula#class Sparknest < Formula\n  version \"$version\"#" \
        packaging/homebrew/sparknest.rb.in
  } > "$out/sparknest.rb"
  echo "packaged $name ($(git rev-parse --short HEAD))"
}

install_host() {
  local h=$1
  ssh "$h" "mkdir -p $DIST_REMOTE"
  rsync -a "$out/$name.tar.gz" "$out/sparknest.rb" "$h:sparknest-dist/"
  ssh "$h" bash -s <<EOF
set -e
export HOMEBREW_NO_AUTO_UPDATE=1
tap=\$($BREW --repository "$TAP")
[ -d "\$tap" ] || $BREW tap-new --no-git "$TAP" >/dev/null
mkdir -p "\$tap/Formula"
cp $DIST_REMOTE/sparknest.rb "\$tap/Formula/sparknest.rb"
if $BREW list --versions sparknest >/dev/null 2>&1; then
  $BREW reinstall --build-from-source "$TAP/sparknest"
else
  $BREW install --build-from-source "$TAP/sparknest"
fi
$BIN/sparknestd --version
EOF
}

install_all() {
  mkdir -p dist/install-logs
  local pids=()
  for h in "${SPARKNEST_HOSTS[@]}"; do
    IFS=: read -r host _ _ _ <<<"$h"
    # `install HOST...` retries only those.
    if [ $# -gt 0 ] && ! printf '%s\n' "$@" | grep -qx "$host"; then continue; fi
    ( install_host "$host" > "dist/install-logs/$host.log" 2>&1 \
        && echo "== $host: $(tail -1 "dist/install-logs/$host.log")" \
        || echo "== $host: FAILED (dist/install-logs/$host.log)" ) &
    pids+=($!)
  done
  for p in "${pids[@]}"; do wait "$p"; done
}

configure() {
  local members="" secret="dist/cluster.secret.$CLUSTER"
  for h in "${SPARKNEST_HOSTS[@]}"; do
    IFS=: read -r host id ip _ <<<"$h"
    members+="  { id = $id, name = \"$host\", addr = \"$ip:$PORT\" },"$'\n'
  done
  [ -f "$secret" ] || { head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n' > "$secret"; chmod 600 "$secret"; }
  for h in "${SPARKNEST_HOSTS[@]}"; do
    IFS=: read -r host id ip _ <<<"$h"
    ssh "$host" "test -w $STATE && test -d $MOUNT && mkdir -p ~/.config/sparknest" \
      || { echo "== $host: $STATE or $MOUNT missing or not writable (root step)"; continue; }
    ssh "$host" "cat > $STATE/node.toml" <<CFG
# Generated by scripts/install-cluster.sh
[node]
id = $id
name = "$host"
state_dir = "$STATE"
mountpoint = "$MOUNT"
listen = "$ip:$PORT"
api_listen = "0.0.0.0:$API_PORT"

[cluster]
name = "$CLUSTER"
secret_file = "$STATE/cluster.secret"
members = [
$members]

[fabric]
mode = "auto"

[fuse]
allow_other = true
io_uring = true
# Passthrough where this host holds the only copy, or reads are scattered;
# files with several copies are read through sparknest, spread over them.
passthrough = "sole"
balance_reads = true

[hf]
home = "/hf-home"
CFG
    rsync -a --chmod=F600 "$secret" "$host:$STATE/cluster.secret"
    user=$(ssh "$host" 'id -un'); group=$(ssh "$host" 'id -gn')
    sed -e "s#@BIN_DIR@#$BIN#g" -e "s#@STATE_DIR@#$STATE#g" -e "s#@MOUNT@#$MOUNT#g" \
        -e "s#@USER@#$user#g" -e "s#@GROUP@#$group#g" \
      packaging/systemd/sparknestd@.service \
      | ssh "$host" "cat > ~/.config/sparknest/sparknestd@$CLUSTER.service"
    ssh "$host" "$BIN/sparknestd --config $STATE/node.toml --check" >/dev/null \
      && echo "== $host: configured" || echo "== $host: config check FAILED"
  done
  cat <<EOF

Root, once per host (installs the unit that runs as you with CAP_SYS_ADMIN,
for passthrough):
  sudo cp ~/.config/sparknest/sparknestd@$CLUSTER.service /etc/systemd/system/ \\
    && sudo systemctl daemon-reload && sudo systemctl enable sparknestd@$CLUSTER
Bootstrap the first host once before starting any (docs/INSTALL.md, "Start").
EOF
}

case "${1:-}" in
  package) package ;;
  install) shift; install_all "$@" ;;
  configure) configure ;;
  all) package && install_all && configure ;;
  *) sed -n '2,17p' "$0" >&2; exit 2 ;;
esac
